### ISSUE TITLE
Avant Garde blocks project from building

### ISSUE THREAD

**Issue by Kacper-Kondracki** [kuiperzone/AvantGarde#30]
Avant Garde blocks project from building for me.
It seems that to reproduce this issue you need to open solution in Avant Garde, open a view to preview and then make some change to xaml code. After that C# project is no longer buildable giving this error message.

```
The process cannot access
the file 'C:\Users\Kacper\RiderProjects\MyApp\MyApp\bin\Debug\net7.0\MyApp.dll' because it is being used by another pro
cess.
```

OS: Windows 11

It would really be nice if I could compile my project without closing Avant Garde.

**Comment by kuiperzone** [comment]
Thank you.

When I first developed this app, this issue did not exist. In recent times, however, I've experienced it myself on Linux and have wondered how got introduced...

Avant Garde itself should not be locking any files. It keeps a tree of file items (PathItem class and subclasses thereof), but this only uses FileInfo and DirectoryInfo internally. Certainly, there is no reason why DLLs should be locked.

Avant Garde does, however, launch the Avalonia "design host" application which does the actual preview generation. I suspect it is this which might be locking the files. I'll do a little investigation on where to pin the "blame". If transpires that it is the design host, then there's nothing which can be done from Avant Garde. If it's AG, however, I'll fix it.

**Comment by kuiperzone** [comment]
Doesn't seem to be doing this any longer, at least on Linux.

**Comment by kuiperzone** [comment]
See linked issue below for updates:

https://github.com/AvaloniaUI/Avalonia/issues/13850

**Comment by HuygheDaphne-Marie** [comment]
@kuiperzone 
I've been using it since there was no way I could find to pop out the design preview. Which provides a nicer development experience for me. I've looked around in their settings and the like and wasn't able to find any method of doing this.

**Comment by kuiperzone** [comment]
Good to know. Thanks

**Comment by kuiperzone** [comment]
I'm hoping this will be "fixed" (twas the preview host that broke it) in version 1.4.
