### ISSUE TITLE
Would you consider adding F# project (*.fsproj) support?

### ISSUE THREAD

**Issue by mimoguz** [kuiperzone/AvantGarde#34]
I think adding "*.fsproj" to the supported types list will do the trick? I've got a fork here that seemingly works: [https://github.com/mimoguz/AvantGarde/tree/fsproj](https://github.com/mimoguz/AvantGarde/tree/fsproj)

Thanks.

**Comment by kuiperzone** [comment]
You are using this with F# apps? And it's working no problems?

**Comment by mimoguz** [comment]
> You are using this with F# apps? And it's working no problems?

I normally use Visual Studio on my desktop, but I've some hardware problems. My notebook runs Linux, and I couldn't get VS Code Avalonia extension work. The fork did work yes. 😊

**Comment by kuiperzone** [comment]
Yes, I'm considering merging your fork into the repo. I don't use F#, and if it meant supporting F# specific features, I'd probably pass for the moment. However, from what I can see F# dlls are binary compatible and I don't see any problems if the only thing to be done is allow the user to select an fsproj file.

But please let me know if there are any issues you find.

Thank you for the feedback.
