### ISSUE TITLE
Windows .exe x64 download reportedly contains virus (trojan)

### ISSUE THREAD

**Issue by SuperJMN** [kuiperzone/AvantGarde#4]
Hello! both browsers I have reported the .exe to contain some virus
![image](https://user-images.githubusercontent.com/3109851/162183129-bf94f52a-6532-43ae-8dec-d034295cc1dd.png)

Windows Defender says that, also.

The link is https://github.com/kuiperzone/AvantGarde/releases/download/v1.0.0/AvantGarde-win-x64.exe

Just to let you know. 
I hope you could fix that soon.

Congratulations for the great work!

**Comment by kuiperzone** [comment]
Thanks for the message.

I'm not seeing this -- no message from Windows Security.

I'm using Windows 10 in VirtualBox which was created with express purpose of building this install, so this machine has not been widely exposed. I've also just ran Kaspersky AntiVirus and not finding anything. If I can confirm there's a problem, I'll fix it.

Glad you like it tho.

**Comment by SuperJMN** [comment]
I'm sorry for this problem :(

I've just recorded a video of the whole flow:
This is the Vivaldi browser, but it says the same with Edge

https://user-images.githubusercontent.com/3109851/162187827-2b061844-667c-4ec9-8fa8-77e5a2e0c08b.mp4

**Comment by MarkusKgit** [comment]
Strange, I am not getting any warning on Windows 10 (Firefox and Kaspersky). 

[VirusTotal ](https://www.virustotal.com/gui/file/a8aca0b0fa23a413dbbc1b2695a4bb7e915700d90a16e0761c37efdb65f68e45) doesn't report anything either?

**Comment by kuiperzone** [comment]
Hey, I certainly believe you. I'm grateful for the message. But like I say, I'm not finding anything this end.

Am wondering if this is a false positive?

https://www.youtube.com/watch?v=wxcIuIs0WcY

**Comment by kuiperzone** [comment]
@MarkusKgit - thank you.
